name: Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: w0058864.kasserver.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./web/" 
          server-dir: "/" 

      - name: FTP Deploy Data
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: w0058864.kasserver.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./data/"
          server-dir: "/data/"